/*
 * Copyright (c) 2009 Stanford University.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in the
 *   documentation and/or other materials provided with the
 *   distribution.
 * - Neither the name of the Stanford University nor the names of
 *   its contributors may be used to endorse or promote products derived
 *   from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL STANFORD
 * UNIVERSITY OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * General-purpose I/O abstraction for the SAM3U.
 * Includes PIO controllers A, B, C with 32 pins each.
 *
 * @author Wanja Hofer <wanja@cs.fau.de>
 */

configuration HplSam3uGeneralIOC
{
	provides {
		interface GeneralIO as PioA0;
		interface GeneralIO as PioA1;
		interface GeneralIO as PioA2;
		interface GeneralIO as PioA3;
		interface GeneralIO as PioA4;
		interface GeneralIO as PioA5;
		interface GeneralIO as PioA6;
		interface GeneralIO as PioA7;
		interface GeneralIO as PioA8;
		interface GeneralIO as PioA9;
		interface GeneralIO as PioA10;
		interface GeneralIO as PioA11;
		interface GeneralIO as PioA12;
		interface GeneralIO as PioA13;
		interface GeneralIO as PioA14;
		interface GeneralIO as PioA15;
		interface GeneralIO as PioA16;
		interface GeneralIO as PioA17;
		interface GeneralIO as PioA18;
		interface GeneralIO as PioA19;
		interface GeneralIO as PioA20;
		interface GeneralIO as PioA21;
		interface GeneralIO as PioA22;
		interface GeneralIO as PioA23;
		interface GeneralIO as PioA24;
		interface GeneralIO as PioA25;
		interface GeneralIO as PioA26;
		interface GeneralIO as PioA27;
		interface GeneralIO as PioA28;
		interface GeneralIO as PioA29;
		interface GeneralIO as PioA30;
		interface GeneralIO as PioA31;

		interface GeneralIO as PioB0;
		interface GeneralIO as PioB1;
		interface GeneralIO as PioB2;
		interface GeneralIO as PioB3;
		interface GeneralIO as PioB4;
		interface GeneralIO as PioB5;
		interface GeneralIO as PioB6;
		interface GeneralIO as PioB7;
		interface GeneralIO as PioB8;
		interface GeneralIO as PioB9;
		interface GeneralIO as PioB10;
		interface GeneralIO as PioB11;
		interface GeneralIO as PioB12;
		interface GeneralIO as PioB13;
		interface GeneralIO as PioB14;
		interface GeneralIO as PioB15;
		interface GeneralIO as PioB16;
		interface GeneralIO as PioB17;
		interface GeneralIO as PioB18;
		interface GeneralIO as PioB19;
		interface GeneralIO as PioB20;
		interface GeneralIO as PioB21;
		interface GeneralIO as PioB22;
		interface GeneralIO as PioB23;
		interface GeneralIO as PioB24;
		interface GeneralIO as PioB25;
		interface GeneralIO as PioB26;
		interface GeneralIO as PioB27;
		interface GeneralIO as PioB28;
		interface GeneralIO as PioB29;
		interface GeneralIO as PioB30;
		interface GeneralIO as PioB31;

		interface GeneralIO as PioC0;
		interface GeneralIO as PioC1;
		interface GeneralIO as PioC2;
		interface GeneralIO as PioC3;
		interface GeneralIO as PioC4;
		interface GeneralIO as PioC5;
		interface GeneralIO as PioC6;
		interface GeneralIO as PioC7;
		interface GeneralIO as PioC8;
		interface GeneralIO as PioC9;
		interface GeneralIO as PioC10;
		interface GeneralIO as PioC11;
		interface GeneralIO as PioC12;
		interface GeneralIO as PioC13;
		interface GeneralIO as PioC14;
		interface GeneralIO as PioC15;
		interface GeneralIO as PioC16;
		interface GeneralIO as PioC17;
		interface GeneralIO as PioC18;
		interface GeneralIO as PioC19;
		interface GeneralIO as PioC20;
		interface GeneralIO as PioC21;
		interface GeneralIO as PioC22;
		interface GeneralIO as PioC23;
		interface GeneralIO as PioC24;
		interface GeneralIO as PioC25;
		interface GeneralIO as PioC26;
		interface GeneralIO as PioC27;
		interface GeneralIO as PioC28;
		interface GeneralIO as PioC29;
		interface GeneralIO as PioC30;
		interface GeneralIO as PioC31;

		interface GpioInterrupt as PioInterruptA0;
		interface GpioInterrupt as PioInterruptA1;
		interface GpioInterrupt as PioInterruptA2;
		interface GpioInterrupt as PioInterruptA3;
		interface GpioInterrupt as PioInterruptA4;
		interface GpioInterrupt as PioInterruptA5;
		interface GpioInterrupt as PioInterruptA6;
		interface GpioInterrupt as PioInterruptA7;
		interface GpioInterrupt as PioInterruptA8;
		interface GpioInterrupt as PioInterruptA9;
		interface GpioInterrupt as PioInterruptA10;
		interface GpioInterrupt as PioInterruptA11;
		interface GpioInterrupt as PioInterruptA12;
		interface GpioInterrupt as PioInterruptA13;
		interface GpioInterrupt as PioInterruptA14;
		interface GpioInterrupt as PioInterruptA15;
		interface GpioInterrupt as PioInterruptA16;
		interface GpioInterrupt as PioInterruptA17;
		interface GpioInterrupt as PioInterruptA18;
		interface GpioInterrupt as PioInterruptA19;
		interface GpioInterrupt as PioInterruptA20;
		interface GpioInterrupt as PioInterruptA21;
		interface GpioInterrupt as PioInterruptA22;
		interface GpioInterrupt as PioInterruptA23;
		interface GpioInterrupt as PioInterruptA24;
		interface GpioInterrupt as PioInterruptA25;
		interface GpioInterrupt as PioInterruptA26;
		interface GpioInterrupt as PioInterruptA27;
		interface GpioInterrupt as PioInterruptA28;
		interface GpioInterrupt as PioInterruptA29;
		interface GpioInterrupt as PioInterruptA30;
		interface GpioInterrupt as PioInterruptA31;

		interface GpioInterrupt as PioInterruptB0;
		interface GpioInterrupt as PioInterruptB1;
		interface GpioInterrupt as PioInterruptB2;
		interface GpioInterrupt as PioInterruptB3;
		interface GpioInterrupt as PioInterruptB4;
		interface GpioInterrupt as PioInterruptB5;
		interface GpioInterrupt as PioInterruptB6;
		interface GpioInterrupt as PioInterruptB7;
		interface GpioInterrupt as PioInterruptB8;
		interface GpioInterrupt as PioInterruptB9;
		interface GpioInterrupt as PioInterruptB10;
		interface GpioInterrupt as PioInterruptB11;
		interface GpioInterrupt as PioInterruptB12;
		interface GpioInterrupt as PioInterruptB13;
		interface GpioInterrupt as PioInterruptB14;
		interface GpioInterrupt as PioInterruptB15;
		interface GpioInterrupt as PioInterruptB16;
		interface GpioInterrupt as PioInterruptB17;
		interface GpioInterrupt as PioInterruptB18;
		interface GpioInterrupt as PioInterruptB19;
		interface GpioInterrupt as PioInterruptB20;
		interface GpioInterrupt as PioInterruptB21;
		interface GpioInterrupt as PioInterruptB22;
		interface GpioInterrupt as PioInterruptB23;
		interface GpioInterrupt as PioInterruptB24;
		interface GpioInterrupt as PioInterruptB25;
		interface GpioInterrupt as PioInterruptB26;
		interface GpioInterrupt as PioInterruptB27;
		interface GpioInterrupt as PioInterruptB28;
		interface GpioInterrupt as PioInterruptB29;
		interface GpioInterrupt as PioInterruptB30;
		interface GpioInterrupt as PioInterruptB31;

		interface GpioInterrupt as PioInterruptC0;
		interface GpioInterrupt as PioInterruptC1;
		interface GpioInterrupt as PioInterruptC2;
		interface GpioInterrupt as PioInterruptC3;
		interface GpioInterrupt as PioInterruptC4;
		interface GpioInterrupt as PioInterruptC5;
		interface GpioInterrupt as PioInterruptC6;
		interface GpioInterrupt as PioInterruptC7;
		interface GpioInterrupt as PioInterruptC8;
		interface GpioInterrupt as PioInterruptC9;
		interface GpioInterrupt as PioInterruptC10;
		interface GpioInterrupt as PioInterruptC11;
		interface GpioInterrupt as PioInterruptC12;
		interface GpioInterrupt as PioInterruptC13;
		interface GpioInterrupt as PioInterruptC14;
		interface GpioInterrupt as PioInterruptC15;
		interface GpioInterrupt as PioInterruptC16;
		interface GpioInterrupt as PioInterruptC17;
		interface GpioInterrupt as PioInterruptC18;
		interface GpioInterrupt as PioInterruptC19;
		interface GpioInterrupt as PioInterruptC20;
		interface GpioInterrupt as PioInterruptC21;
		interface GpioInterrupt as PioInterruptC22;
		interface GpioInterrupt as PioInterruptC23;
		interface GpioInterrupt as PioInterruptC24;
		interface GpioInterrupt as PioInterruptC25;
		interface GpioInterrupt as PioInterruptC26;
		interface GpioInterrupt as PioInterruptC27;
		interface GpioInterrupt as PioInterruptC28;
		interface GpioInterrupt as PioInterruptC29;
		interface GpioInterrupt as PioInterruptC30;
		interface GpioInterrupt as PioInterruptC31;

		interface GpioCapture as PioCaptureA0;
		interface GpioCapture as PioCaptureA1;
		interface GpioCapture as PioCaptureA2;
		interface GpioCapture as PioCaptureA3;
		interface GpioCapture as PioCaptureA4;
		interface GpioCapture as PioCaptureA5;
		interface GpioCapture as PioCaptureA6;
		interface GpioCapture as PioCaptureA7;
		interface GpioCapture as PioCaptureA8;
		interface GpioCapture as PioCaptureA9;
		interface GpioCapture as PioCaptureA10;
		interface GpioCapture as PioCaptureA11;
		interface GpioCapture as PioCaptureA12;
		interface GpioCapture as PioCaptureA13;
		interface GpioCapture as PioCaptureA14;
		interface GpioCapture as PioCaptureA15;
		interface GpioCapture as PioCaptureA16;
		interface GpioCapture as PioCaptureA17;
		interface GpioCapture as PioCaptureA18;
		interface GpioCapture as PioCaptureA19;
		interface GpioCapture as PioCaptureA20;
		interface GpioCapture as PioCaptureA21;
		interface GpioCapture as PioCaptureA22;
		interface GpioCapture as PioCaptureA23;
		interface GpioCapture as PioCaptureA24;
		interface GpioCapture as PioCaptureA25;
		interface GpioCapture as PioCaptureA26;
		interface GpioCapture as PioCaptureA27;
		interface GpioCapture as PioCaptureA28;
		interface GpioCapture as PioCaptureA29;
		interface GpioCapture as PioCaptureA30;
		interface GpioCapture as PioCaptureA31;

		interface GpioCapture as PioCaptureB0;
		interface GpioCapture as PioCaptureB1;
		interface GpioCapture as PioCaptureB2;
		interface GpioCapture as PioCaptureB3;
		interface GpioCapture as PioCaptureB4;
		interface GpioCapture as PioCaptureB5;
		interface GpioCapture as PioCaptureB6;
		interface GpioCapture as PioCaptureB7;
		interface GpioCapture as PioCaptureB8;
		interface GpioCapture as PioCaptureB9;
		interface GpioCapture as PioCaptureB10;
		interface GpioCapture as PioCaptureB11;
		interface GpioCapture as PioCaptureB12;
		interface GpioCapture as PioCaptureB13;
		interface GpioCapture as PioCaptureB14;
		interface GpioCapture as PioCaptureB15;
		interface GpioCapture as PioCaptureB16;
		interface GpioCapture as PioCaptureB17;
		interface GpioCapture as PioCaptureB18;
		interface GpioCapture as PioCaptureB19;
		interface GpioCapture as PioCaptureB20;
		interface GpioCapture as PioCaptureB21;
		interface GpioCapture as PioCaptureB22;
		interface GpioCapture as PioCaptureB23;
		interface GpioCapture as PioCaptureB24;
		interface GpioCapture as PioCaptureB25;
		interface GpioCapture as PioCaptureB26;
		interface GpioCapture as PioCaptureB27;
		interface GpioCapture as PioCaptureB28;
		interface GpioCapture as PioCaptureB29;
		interface GpioCapture as PioCaptureB30;
		interface GpioCapture as PioCaptureB31;

		interface GpioCapture as PioCaptureC0;
		interface GpioCapture as PioCaptureC1;
		interface GpioCapture as PioCaptureC2;
		interface GpioCapture as PioCaptureC3;
		interface GpioCapture as PioCaptureC4;
		interface GpioCapture as PioCaptureC5;
		interface GpioCapture as PioCaptureC6;
		interface GpioCapture as PioCaptureC7;
		interface GpioCapture as PioCaptureC8;
		interface GpioCapture as PioCaptureC9;
		interface GpioCapture as PioCaptureC10;
		interface GpioCapture as PioCaptureC11;
		interface GpioCapture as PioCaptureC12;
		interface GpioCapture as PioCaptureC13;
		interface GpioCapture as PioCaptureC14;
		interface GpioCapture as PioCaptureC15;
		interface GpioCapture as PioCaptureC16;
		interface GpioCapture as PioCaptureC17;
		interface GpioCapture as PioCaptureC18;
		interface GpioCapture as PioCaptureC19;
		interface GpioCapture as PioCaptureC20;
		interface GpioCapture as PioCaptureC21;
		interface GpioCapture as PioCaptureC22;
		interface GpioCapture as PioCaptureC23;
		interface GpioCapture as PioCaptureC24;
		interface GpioCapture as PioCaptureC25;
		interface GpioCapture as PioCaptureC26;
		interface GpioCapture as PioCaptureC27;
		interface GpioCapture as PioCaptureC28;
		interface GpioCapture as PioCaptureC29;
		interface GpioCapture as PioCaptureC30;
		interface GpioCapture as PioCaptureC31;

		interface HplSam3uGeneralIOPin as HplPioA0;
		interface HplSam3uGeneralIOPin as HplPioA1;
		interface HplSam3uGeneralIOPin as HplPioA2;
		interface HplSam3uGeneralIOPin as HplPioA3;
		interface HplSam3uGeneralIOPin as HplPioA4;
		interface HplSam3uGeneralIOPin as HplPioA5;
		interface HplSam3uGeneralIOPin as HplPioA6;
		interface HplSam3uGeneralIOPin as HplPioA7;
		interface HplSam3uGeneralIOPin as HplPioA8;
		interface HplSam3uGeneralIOPin as HplPioA9;
		interface HplSam3uGeneralIOPin as HplPioA10;
		interface HplSam3uGeneralIOPin as HplPioA11;
		interface HplSam3uGeneralIOPin as HplPioA12;
		interface HplSam3uGeneralIOPin as HplPioA13;
		interface HplSam3uGeneralIOPin as HplPioA14;
		interface HplSam3uGeneralIOPin as HplPioA15;
		interface HplSam3uGeneralIOPin as HplPioA16;
		interface HplSam3uGeneralIOPin as HplPioA17;
		interface HplSam3uGeneralIOPin as HplPioA18;
		interface HplSam3uGeneralIOPin as HplPioA19;
		interface HplSam3uGeneralIOPin as HplPioA20;
		interface HplSam3uGeneralIOPin as HplPioA21;
		interface HplSam3uGeneralIOPin as HplPioA22;
		interface HplSam3uGeneralIOPin as HplPioA23;
		interface HplSam3uGeneralIOPin as HplPioA24;
		interface HplSam3uGeneralIOPin as HplPioA25;
		interface HplSam3uGeneralIOPin as HplPioA26;
		interface HplSam3uGeneralIOPin as HplPioA27;
		interface HplSam3uGeneralIOPin as HplPioA28;
		interface HplSam3uGeneralIOPin as HplPioA29;
		interface HplSam3uGeneralIOPin as HplPioA30;
		interface HplSam3uGeneralIOPin as HplPioA31;

		interface HplSam3uGeneralIOPin as HplPioB0;
		interface HplSam3uGeneralIOPin as HplPioB1;
		interface HplSam3uGeneralIOPin as HplPioB2;
		interface HplSam3uGeneralIOPin as HplPioB3;
		interface HplSam3uGeneralIOPin as HplPioB4;
		interface HplSam3uGeneralIOPin as HplPioB5;
		interface HplSam3uGeneralIOPin as HplPioB6;
		interface HplSam3uGeneralIOPin as HplPioB7;
		interface HplSam3uGeneralIOPin as HplPioB8;
		interface HplSam3uGeneralIOPin as HplPioB9;
		interface HplSam3uGeneralIOPin as HplPioB10;
		interface HplSam3uGeneralIOPin as HplPioB11;
		interface HplSam3uGeneralIOPin as HplPioB12;
		interface HplSam3uGeneralIOPin as HplPioB13;
		interface HplSam3uGeneralIOPin as HplPioB14;
		interface HplSam3uGeneralIOPin as HplPioB15;
		interface HplSam3uGeneralIOPin as HplPioB16;
		interface HplSam3uGeneralIOPin as HplPioB17;
		interface HplSam3uGeneralIOPin as HplPioB18;
		interface HplSam3uGeneralIOPin as HplPioB19;
		interface HplSam3uGeneralIOPin as HplPioB20;
		interface HplSam3uGeneralIOPin as HplPioB21;
		interface HplSam3uGeneralIOPin as HplPioB22;
		interface HplSam3uGeneralIOPin as HplPioB23;
		interface HplSam3uGeneralIOPin as HplPioB24;
		interface HplSam3uGeneralIOPin as HplPioB25;
		interface HplSam3uGeneralIOPin as HplPioB26;
		interface HplSam3uGeneralIOPin as HplPioB27;
		interface HplSam3uGeneralIOPin as HplPioB28;
		interface HplSam3uGeneralIOPin as HplPioB29;
		interface HplSam3uGeneralIOPin as HplPioB30;
		interface HplSam3uGeneralIOPin as HplPioB31;

		interface HplSam3uGeneralIOPin as HplPioC0;
		interface HplSam3uGeneralIOPin as HplPioC1;
		interface HplSam3uGeneralIOPin as HplPioC2;
		interface HplSam3uGeneralIOPin as HplPioC3;
		interface HplSam3uGeneralIOPin as HplPioC4;
		interface HplSam3uGeneralIOPin as HplPioC5;
		interface HplSam3uGeneralIOPin as HplPioC6;
		interface HplSam3uGeneralIOPin as HplPioC7;
		interface HplSam3uGeneralIOPin as HplPioC8;
		interface HplSam3uGeneralIOPin as HplPioC9;
		interface HplSam3uGeneralIOPin as HplPioC10;
		interface HplSam3uGeneralIOPin as HplPioC11;
		interface HplSam3uGeneralIOPin as HplPioC12;
		interface HplSam3uGeneralIOPin as HplPioC13;
		interface HplSam3uGeneralIOPin as HplPioC14;
		interface HplSam3uGeneralIOPin as HplPioC15;
		interface HplSam3uGeneralIOPin as HplPioC16;
		interface HplSam3uGeneralIOPin as HplPioC17;
		interface HplSam3uGeneralIOPin as HplPioC18;
		interface HplSam3uGeneralIOPin as HplPioC19;
		interface HplSam3uGeneralIOPin as HplPioC20;
		interface HplSam3uGeneralIOPin as HplPioC21;
		interface HplSam3uGeneralIOPin as HplPioC22;
		interface HplSam3uGeneralIOPin as HplPioC23;
		interface HplSam3uGeneralIOPin as HplPioC24;
		interface HplSam3uGeneralIOPin as HplPioC25;
		interface HplSam3uGeneralIOPin as HplPioC26;
		interface HplSam3uGeneralIOPin as HplPioC27;
		interface HplSam3uGeneralIOPin as HplPioC28;
		interface HplSam3uGeneralIOPin as HplPioC29;
		interface HplSam3uGeneralIOPin as HplPioC30;
		interface HplSam3uGeneralIOPin as HplPioC31;
	}
}

implementation
{
	components 
	new HplSam3uGeneralIOPioC(0x400e0c00) as PioA,
	new HplSam3uGeneralIOPioC(0x400e0e00) as PioB,
	new HplSam3uGeneralIOPioC(0x400e1000) as PioC;

    components HplSam3uGeneralIOP;
    PioA.HplPort -> HplSam3uGeneralIOP.HplPortA;
    PioB.HplPort -> HplSam3uGeneralIOP.HplPortB;
    PioC.HplPort -> HplSam3uGeneralIOP.HplPortC;

    components HplNVICC, HplSam3uClockC;
    PioA.PIOIrqControl -> HplNVICC.PIOAInterrupt;
    PioA.PIOClockControl -> HplSam3uClockC.PIOAPPCntl;
    PioB.PIOIrqControl -> HplNVICC.PIOBInterrupt;
    PioB.PIOClockControl -> HplSam3uClockC.PIOBPPCntl;
    PioC.PIOIrqControl -> HplNVICC.PIOCInterrupt;
    PioC.PIOClockControl -> HplSam3uClockC.PIOCPPCntl;

	PioA0 = PioA.Pin0;
	PioA1 = PioA.Pin1;
	PioA2 = PioA.Pin2;
	PioA3 = PioA.Pin3;
	PioA4 = PioA.Pin4;
	PioA5 = PioA.Pin5;
	PioA6 = PioA.Pin6;
	PioA7 = PioA.Pin7;
	PioA8 = PioA.Pin8;
	PioA9 = PioA.Pin9;
	PioA10 = PioA.Pin10;
	PioA11 = PioA.Pin11;
	PioA12 = PioA.Pin12;
	PioA13 = PioA.Pin13;
	PioA14 = PioA.Pin14;
	PioA15 = PioA.Pin15;
	PioA16 = PioA.Pin16;
	PioA17 = PioA.Pin17;
	PioA18 = PioA.Pin18;
	PioA19 = PioA.Pin19;
	PioA20 = PioA.Pin20;
	PioA21 = PioA.Pin21;
	PioA22 = PioA.Pin22;
	PioA23 = PioA.Pin23;
	PioA24 = PioA.Pin24;
	PioA25 = PioA.Pin25;
	PioA26 = PioA.Pin26;
	PioA27 = PioA.Pin27;
	PioA28 = PioA.Pin28;
	PioA29 = PioA.Pin29;
	PioA30 = PioA.Pin30;
	PioA31 = PioA.Pin31;

	PioB0 = PioB.Pin0;
	PioB1 = PioB.Pin1;
	PioB2 = PioB.Pin2;
	PioB3 = PioB.Pin3;
	PioB4 = PioB.Pin4;
	PioB5 = PioB.Pin5;
	PioB6 = PioB.Pin6;
	PioB7 = PioB.Pin7;
	PioB8 = PioB.Pin8;
	PioB9 = PioB.Pin9;
	PioB10 = PioB.Pin10;
	PioB11 = PioB.Pin11;
	PioB12 = PioB.Pin12;
	PioB13 = PioB.Pin13;
	PioB14 = PioB.Pin14;
	PioB15 = PioB.Pin15;
	PioB16 = PioB.Pin16;
	PioB17 = PioB.Pin17;
	PioB18 = PioB.Pin18;
	PioB19 = PioB.Pin19;
	PioB20 = PioB.Pin20;
	PioB21 = PioB.Pin21;
	PioB22 = PioB.Pin22;
	PioB23 = PioB.Pin23;
	PioB24 = PioB.Pin24;
	PioB25 = PioB.Pin25;
	PioB26 = PioB.Pin26;
	PioB27 = PioB.Pin27;
	PioB28 = PioB.Pin28;
	PioB29 = PioB.Pin29;
	PioB30 = PioB.Pin30;
	PioB31 = PioB.Pin31;

	PioC0 = PioC.Pin0;
	PioC1 = PioC.Pin1;
	PioC2 = PioC.Pin2;
	PioC3 = PioC.Pin3;
	PioC4 = PioC.Pin4;
	PioC5 = PioC.Pin5;
	PioC6 = PioC.Pin6;
	PioC7 = PioC.Pin7;
	PioC8 = PioC.Pin8;
	PioC9 = PioC.Pin9;
	PioC10 = PioC.Pin10;
	PioC11 = PioC.Pin11;
	PioC12 = PioC.Pin12;
	PioC13 = PioC.Pin13;
	PioC14 = PioC.Pin14;
	PioC15 = PioC.Pin15;
	PioC16 = PioC.Pin16;
	PioC17 = PioC.Pin17;
	PioC18 = PioC.Pin18;
	PioC19 = PioC.Pin19;
	PioC20 = PioC.Pin20;
	PioC21 = PioC.Pin21;
	PioC22 = PioC.Pin22;
	PioC23 = PioC.Pin23;
	PioC24 = PioC.Pin24;
	PioC25 = PioC.Pin25;
	PioC26 = PioC.Pin26;
	PioC27 = PioC.Pin27;
	PioC28 = PioC.Pin28;
	PioC29 = PioC.Pin29;
	PioC30 = PioC.Pin30;
	PioC31 = PioC.Pin31;

	PioInterruptA0 = PioA.InterruptPin0;
	PioInterruptA1 = PioA.InterruptPin1;
	PioInterruptA2 = PioA.InterruptPin2;
	PioInterruptA3 = PioA.InterruptPin3;
	PioInterruptA4 = PioA.InterruptPin4;
	PioInterruptA5 = PioA.InterruptPin5;
	PioInterruptA6 = PioA.InterruptPin6;
	PioInterruptA7 = PioA.InterruptPin7;
	PioInterruptA8 = PioA.InterruptPin8;
	PioInterruptA9 = PioA.InterruptPin9;
	PioInterruptA10 = PioA.InterruptPin10;
	PioInterruptA11 = PioA.InterruptPin11;
	PioInterruptA12 = PioA.InterruptPin12;
	PioInterruptA13 = PioA.InterruptPin13;
	PioInterruptA14 = PioA.InterruptPin14;
	PioInterruptA15 = PioA.InterruptPin15;
	PioInterruptA16 = PioA.InterruptPin16;
	PioInterruptA17 = PioA.InterruptPin17;
	PioInterruptA18 = PioA.InterruptPin18;
	PioInterruptA19 = PioA.InterruptPin19;
	PioInterruptA20 = PioA.InterruptPin20;
	PioInterruptA21 = PioA.InterruptPin21;
	PioInterruptA22 = PioA.InterruptPin22;
	PioInterruptA23 = PioA.InterruptPin23;
	PioInterruptA24 = PioA.InterruptPin24;
	PioInterruptA25 = PioA.InterruptPin25;
	PioInterruptA26 = PioA.InterruptPin26;
	PioInterruptA27 = PioA.InterruptPin27;
	PioInterruptA28 = PioA.InterruptPin28;
	PioInterruptA29 = PioA.InterruptPin29;
	PioInterruptA30 = PioA.InterruptPin30;
	PioInterruptA31 = PioA.InterruptPin31;

	PioInterruptB0 = PioB.InterruptPin0;
	PioInterruptB1 = PioB.InterruptPin1;
	PioInterruptB2 = PioB.InterruptPin2;
	PioInterruptB3 = PioB.InterruptPin3;
	PioInterruptB4 = PioB.InterruptPin4;
	PioInterruptB5 = PioB.InterruptPin5;
	PioInterruptB6 = PioB.InterruptPin6;
	PioInterruptB7 = PioB.InterruptPin7;
	PioInterruptB8 = PioB.InterruptPin8;
	PioInterruptB9 = PioB.InterruptPin9;
	PioInterruptB10 = PioB.InterruptPin10;
	PioInterruptB11 = PioB.InterruptPin11;
	PioInterruptB12 = PioB.InterruptPin12;
	PioInterruptB13 = PioB.InterruptPin13;
	PioInterruptB14 = PioB.InterruptPin14;
	PioInterruptB15 = PioB.InterruptPin15;
	PioInterruptB16 = PioB.InterruptPin16;
	PioInterruptB17 = PioB.InterruptPin17;
	PioInterruptB18 = PioB.InterruptPin18;
	PioInterruptB19 = PioB.InterruptPin19;
	PioInterruptB20 = PioB.InterruptPin20;
	PioInterruptB21 = PioB.InterruptPin21;
	PioInterruptB22 = PioB.InterruptPin22;
	PioInterruptB23 = PioB.InterruptPin23;
	PioInterruptB24 = PioB.InterruptPin24;
	PioInterruptB25 = PioB.InterruptPin25;
	PioInterruptB26 = PioB.InterruptPin26;
	PioInterruptB27 = PioB.InterruptPin27;
	PioInterruptB28 = PioB.InterruptPin28;
	PioInterruptB29 = PioB.InterruptPin29;
	PioInterruptB30 = PioB.InterruptPin30;
	PioInterruptB31 = PioB.InterruptPin31;

	PioInterruptC0 = PioC.InterruptPin0;
	PioInterruptC1 = PioC.InterruptPin1;
	PioInterruptC2 = PioC.InterruptPin2;
	PioInterruptC3 = PioC.InterruptPin3;
	PioInterruptC4 = PioC.InterruptPin4;
	PioInterruptC5 = PioC.InterruptPin5;
	PioInterruptC6 = PioC.InterruptPin6;
	PioInterruptC7 = PioC.InterruptPin7;
	PioInterruptC8 = PioC.InterruptPin8;
	PioInterruptC9 = PioC.InterruptPin9;
	PioInterruptC10 = PioC.InterruptPin10;
	PioInterruptC11 = PioC.InterruptPin11;
	PioInterruptC12 = PioC.InterruptPin12;
	PioInterruptC13 = PioC.InterruptPin13;
	PioInterruptC14 = PioC.InterruptPin14;
	PioInterruptC15 = PioC.InterruptPin15;
	PioInterruptC16 = PioC.InterruptPin16;
	PioInterruptC17 = PioC.InterruptPin17;
	PioInterruptC18 = PioC.InterruptPin18;
	PioInterruptC19 = PioC.InterruptPin19;
	PioInterruptC20 = PioC.InterruptPin20;
	PioInterruptC21 = PioC.InterruptPin21;
	PioInterruptC22 = PioC.InterruptPin22;
	PioInterruptC23 = PioC.InterruptPin23;
	PioInterruptC24 = PioC.InterruptPin24;
	PioInterruptC25 = PioC.InterruptPin25;
	PioInterruptC26 = PioC.InterruptPin26;
	PioInterruptC27 = PioC.InterruptPin27;
	PioInterruptC28 = PioC.InterruptPin28;
	PioInterruptC29 = PioC.InterruptPin29;
	PioInterruptC30 = PioC.InterruptPin30;
	PioInterruptC31 = PioC.InterruptPin31;

	PioCaptureA0 = PioA.CapturePin0;
	PioCaptureA1 = PioA.CapturePin1;
	PioCaptureA2 = PioA.CapturePin2;
	PioCaptureA3 = PioA.CapturePin3;
	PioCaptureA4 = PioA.CapturePin4;
	PioCaptureA5 = PioA.CapturePin5;
	PioCaptureA6 = PioA.CapturePin6;
	PioCaptureA7 = PioA.CapturePin7;
	PioCaptureA8 = PioA.CapturePin8;
	PioCaptureA9 = PioA.CapturePin9;
	PioCaptureA10 = PioA.CapturePin10;
	PioCaptureA11 = PioA.CapturePin11;
	PioCaptureA12 = PioA.CapturePin12;
	PioCaptureA13 = PioA.CapturePin13;
	PioCaptureA14 = PioA.CapturePin14;
	PioCaptureA15 = PioA.CapturePin15;
	PioCaptureA16 = PioA.CapturePin16;
	PioCaptureA17 = PioA.CapturePin17;
	PioCaptureA18 = PioA.CapturePin18;
	PioCaptureA19 = PioA.CapturePin19;
	PioCaptureA20 = PioA.CapturePin20;
	PioCaptureA21 = PioA.CapturePin21;
	PioCaptureA22 = PioA.CapturePin22;
	PioCaptureA23 = PioA.CapturePin23;
	PioCaptureA24 = PioA.CapturePin24;
	PioCaptureA25 = PioA.CapturePin25;
	PioCaptureA26 = PioA.CapturePin26;
	PioCaptureA27 = PioA.CapturePin27;
	PioCaptureA28 = PioA.CapturePin28;
	PioCaptureA29 = PioA.CapturePin29;
	PioCaptureA30 = PioA.CapturePin30;
	PioCaptureA31 = PioA.CapturePin31;

	PioCaptureB0 = PioB.CapturePin0;
	PioCaptureB1 = PioB.CapturePin1;
	PioCaptureB2 = PioB.CapturePin2;
	PioCaptureB3 = PioB.CapturePin3;
	PioCaptureB4 = PioB.CapturePin4;
	PioCaptureB5 = PioB.CapturePin5;
	PioCaptureB6 = PioB.CapturePin6;
	PioCaptureB7 = PioB.CapturePin7;
	PioCaptureB8 = PioB.CapturePin8;
	PioCaptureB9 = PioB.CapturePin9;
	PioCaptureB10 = PioB.CapturePin10;
	PioCaptureB11 = PioB.CapturePin11;
	PioCaptureB12 = PioB.CapturePin12;
	PioCaptureB13 = PioB.CapturePin13;
	PioCaptureB14 = PioB.CapturePin14;
	PioCaptureB15 = PioB.CapturePin15;
	PioCaptureB16 = PioB.CapturePin16;
	PioCaptureB17 = PioB.CapturePin17;
	PioCaptureB18 = PioB.CapturePin18;
	PioCaptureB19 = PioB.CapturePin19;
	PioCaptureB20 = PioB.CapturePin20;
	PioCaptureB21 = PioB.CapturePin21;
	PioCaptureB22 = PioB.CapturePin22;
	PioCaptureB23 = PioB.CapturePin23;
	PioCaptureB24 = PioB.CapturePin24;
	PioCaptureB25 = PioB.CapturePin25;
	PioCaptureB26 = PioB.CapturePin26;
	PioCaptureB27 = PioB.CapturePin27;
	PioCaptureB28 = PioB.CapturePin28;
	PioCaptureB29 = PioB.CapturePin29;
	PioCaptureB30 = PioB.CapturePin30;
	PioCaptureB31 = PioB.CapturePin31;

	PioCaptureC0 = PioC.CapturePin0;
	PioCaptureC1 = PioC.CapturePin1;
	PioCaptureC2 = PioC.CapturePin2;
	PioCaptureC3 = PioC.CapturePin3;
	PioCaptureC4 = PioC.CapturePin4;
	PioCaptureC5 = PioC.CapturePin5;
	PioCaptureC6 = PioC.CapturePin6;
	PioCaptureC7 = PioC.CapturePin7;
	PioCaptureC8 = PioC.CapturePin8;
	PioCaptureC9 = PioC.CapturePin9;
	PioCaptureC10 = PioC.CapturePin10;
	PioCaptureC11 = PioC.CapturePin11;
	PioCaptureC12 = PioC.CapturePin12;
	PioCaptureC13 = PioC.CapturePin13;
	PioCaptureC14 = PioC.CapturePin14;
	PioCaptureC15 = PioC.CapturePin15;
	PioCaptureC16 = PioC.CapturePin16;
	PioCaptureC17 = PioC.CapturePin17;
	PioCaptureC18 = PioC.CapturePin18;
	PioCaptureC19 = PioC.CapturePin19;
	PioCaptureC20 = PioC.CapturePin20;
	PioCaptureC21 = PioC.CapturePin21;
	PioCaptureC22 = PioC.CapturePin22;
	PioCaptureC23 = PioC.CapturePin23;
	PioCaptureC24 = PioC.CapturePin24;
	PioCaptureC25 = PioC.CapturePin25;
	PioCaptureC26 = PioC.CapturePin26;
	PioCaptureC27 = PioC.CapturePin27;
	PioCaptureC28 = PioC.CapturePin28;
	PioCaptureC29 = PioC.CapturePin29;
	PioCaptureC30 = PioC.CapturePin30;
	PioCaptureC31 = PioC.CapturePin31;

	HplPioA0 = PioA.HplPin0;
	HplPioA1 = PioA.HplPin1;
	HplPioA2 = PioA.HplPin2;
	HplPioA3 = PioA.HplPin3;
	HplPioA4 = PioA.HplPin4;
	HplPioA5 = PioA.HplPin5;
	HplPioA6 = PioA.HplPin6;
	HplPioA7 = PioA.HplPin7;
	HplPioA8 = PioA.HplPin8;
	HplPioA9 = PioA.HplPin9;
	HplPioA10 = PioA.HplPin10;
	HplPioA11 = PioA.HplPin11;
	HplPioA12 = PioA.HplPin12;
	HplPioA13 = PioA.HplPin13;
	HplPioA14 = PioA.HplPin14;
	HplPioA15 = PioA.HplPin15;
	HplPioA16 = PioA.HplPin16;
	HplPioA17 = PioA.HplPin17;
	HplPioA18 = PioA.HplPin18;
	HplPioA19 = PioA.HplPin19;
	HplPioA20 = PioA.HplPin20;
	HplPioA21 = PioA.HplPin21;
	HplPioA22 = PioA.HplPin22;
	HplPioA23 = PioA.HplPin23;
	HplPioA24 = PioA.HplPin24;
	HplPioA25 = PioA.HplPin25;
	HplPioA26 = PioA.HplPin26;
	HplPioA27 = PioA.HplPin27;
	HplPioA28 = PioA.HplPin28;
	HplPioA29 = PioA.HplPin29;
	HplPioA30 = PioA.HplPin30;
	HplPioA31 = PioA.HplPin31;

	HplPioB0 = PioB.HplPin0;
	HplPioB1 = PioB.HplPin1;
	HplPioB2 = PioB.HplPin2;
	HplPioB3 = PioB.HplPin3;
	HplPioB4 = PioB.HplPin4;
	HplPioB5 = PioB.HplPin5;
	HplPioB6 = PioB.HplPin6;
	HplPioB7 = PioB.HplPin7;
	HplPioB8 = PioB.HplPin8;
	HplPioB9 = PioB.HplPin9;
	HplPioB10 = PioB.HplPin10;
	HplPioB11 = PioB.HplPin11;
	HplPioB12 = PioB.HplPin12;
	HplPioB13 = PioB.HplPin13;
	HplPioB14 = PioB.HplPin14;
	HplPioB15 = PioB.HplPin15;
	HplPioB16 = PioB.HplPin16;
	HplPioB17 = PioB.HplPin17;
	HplPioB18 = PioB.HplPin18;
	HplPioB19 = PioB.HplPin19;
	HplPioB20 = PioB.HplPin20;
	HplPioB21 = PioB.HplPin21;
	HplPioB22 = PioB.HplPin22;
	HplPioB23 = PioB.HplPin23;
	HplPioB24 = PioB.HplPin24;
	HplPioB25 = PioB.HplPin25;
	HplPioB26 = PioB.HplPin26;
	HplPioB27 = PioB.HplPin27;
	HplPioB28 = PioB.HplPin28;
	HplPioB29 = PioB.HplPin29;
	HplPioB30 = PioB.HplPin30;
	HplPioB31 = PioB.HplPin31;

	HplPioC0 = PioC.HplPin0;
	HplPioC1 = PioC.HplPin1;
	HplPioC2 = PioC.HplPin2;
	HplPioC3 = PioC.HplPin3;
	HplPioC4 = PioC.HplPin4;
	HplPioC5 = PioC.HplPin5;
	HplPioC6 = PioC.HplPin6;
	HplPioC7 = PioC.HplPin7;
	HplPioC8 = PioC.HplPin8;
	HplPioC9 = PioC.HplPin9;
	HplPioC10 = PioC.HplPin10;
	HplPioC11 = PioC.HplPin11;
	HplPioC12 = PioC.HplPin12;
	HplPioC13 = PioC.HplPin13;
	HplPioC14 = PioC.HplPin14;
	HplPioC15 = PioC.HplPin15;
	HplPioC16 = PioC.HplPin16;
	HplPioC17 = PioC.HplPin17;
	HplPioC18 = PioC.HplPin18;
	HplPioC19 = PioC.HplPin19;
	HplPioC20 = PioC.HplPin20;
	HplPioC21 = PioC.HplPin21;
	HplPioC22 = PioC.HplPin22;
	HplPioC23 = PioC.HplPin23;
	HplPioC24 = PioC.HplPin24;
	HplPioC25 = PioC.HplPin25;
	HplPioC26 = PioC.HplPin26;
	HplPioC27 = PioC.HplPin27;
	HplPioC28 = PioC.HplPin28;
	HplPioC29 = PioC.HplPin29;
	HplPioC30 = PioC.HplPin30;
	HplPioC31 = PioC.HplPin31;
}
